apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: lab01-data
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9092
          resources: {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: KAFKA_PROCESS_ROLES
              value: "{{ .Values.kafka.processRoles }}"
            - name: KAFKA_NODE_ID
              value: "{{ .Values.kafka.nodeId }}"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "{{ .Values.kafka.controllerQuorumVoters }}"
            - name: KAFKA_LISTENERS
              value: "{{ .Values.kafka.listeners }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "{{ .Values.kafka.advertisedListeners }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "{{ .Values.kafka.listenerSecurityProtocolMap }}"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: lab01-data
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9092
  selector:
    app: kafka
