replicaCount: 1
image:
  repository: docker.io/apache/kafka
  tag: 3.9.1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9092

# KRaft mode configuration (no ZooKeeper)
resources: {}
kafka:
  processRoles: "broker,controller"
  nodeId: 1
  controllerQuorumVoters: "1@localhost:9093"
  listeners: "PLAINTEXT://:9092,CONTROLLER://:9093"
  advertisedListeners: "PLAINTEXT://kafka.lab01-data.svc.cluster.local:9092"
  listenerSecurityProtocolMap: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
