apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1433
      protocol: TCP
      name: tcp
  selector:
    app: mssql
